// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psgyytmlxmfqdsxbcgph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZ3l5dG1seG1mcWRzeGJjZ3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzYyNjcsImV4cCI6MjA3MTM1MjI2N30.VCu-y05pdfTBS4CKzjaEnoEn-OZRC2fDPQv0LUkMkPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});